### PR TITLE
fix: use app provider validator url

### LINKED ISSUE #616: bug: grantFeatureAppRights doesn't work in the setup-exchange.ts
In the exchange scripts when setting the grantFeatureAppRights e.g. 

```
const { treasuryParty, exchangeSdk } = await setupExchange({
    transferPreapproval: true,
    grantFeatureAppRights: true
})

```

We get the following error from the sdk:

```
[08:04:25.769] ERROR (setup-exchange/54203):
    code: "NA"
    cause: "A security-sensitive error has been received"
    correlationId: "e3c48ee6df6cce7a56313531f3603026"
    traceId: "e3c48ee6df6cce7a56313531f3603026"
    context: {}
    resources: []
    errorCategory: -1
    grpcCodeValue: 7
    retryInfo: null
    definiteAnswer: null

```

And these errors in the canton logs: 

```
{"@timestamp":"2025-10-06T14:04:25.764Z","message":"Request com.daml.ledger.api.v2.StateService/GetConnectedSynchronizers by inprocess-grpc-3901: received a message \n  Request tid:e3c48ee6df6cce7a56313531f3603026","logger_name":"c.d.c.n.g.ApiRequestLogger:participant=app-provider","thread_name":"canton-env-ec-147","level":"DEBUG","trace-id":"e3c48ee6df6cce7a56313531f3603026"}
{"@timestamp":"2025-10-06T14:04:25.765Z","message":"PERMISSION_DENIED(7,e3c48ee6): Claims do not authorize to read data for party 'app_user_localnet-localparty-1::1220f461716bf68219ff32399a23397fac27fb6bb8ee6aefc540d52a7030d27bc919'","logger_name":"c.d.c.a.Authorizer:participant=app-provider","thread_name":"canton-env-ec-147","level":"WARN","location":"Authorizer.scala:147","error-code":"PERMISSION_DENIED(7,e3c48ee6)","trace-id":"e3c48ee6df6cce7a56313531f3603026","participant":"app-provider"}
{"@timestamp":"2025-10-06T14:04:25.765Z","message":"Request com.daml.ledger.api.v2.StateService/GetConnectedSynchronizers by inprocess-grpc-3901: failed with PERMISSION_DENIED/An error occurred. Please contact the operator and inquire about the request e3c48ee6df6cce7a56313531f3603026 with tid e3c48ee6df6cce7a56313531f3603026","logger_name":"c.d.c.n.g.ApiRequestLogger:participant=app-provider","thread_name":"ForkJoinPool-12-worker-2","level":"INFO","trace-id":"e3c48ee6df6cce7a56313531f3603026"}
{"@timestamp":"2025-10-06T14:04:25.765Z","message":"Request com.daml.ledger.api.v2.StateService/GetConnectedSynchronizers by inprocess-grpc-3901: completed","logger_name":"c.d.c.n.g.ApiRequestLogger:participant=app-provider","thread_name":"canton-env-ec-147","level":"DEBUG","trace-id":"e3c48ee6df6cce7a56313531f3603026"}

```

However, the same code works in [05-token-standard-transfer-autoaccept.ts](https://github.com/hyperledger-labs/splice-wallet-kernel/blob/eb807a36b28de3820e9b0e9289a2f9426fa5bda2/docs/wallet-integration-guide/examples/scripts/05-token-standard-transfer-autoaccept.ts#L163-L171), so we use this as a reference to fix this.

### PR DESCRIPTION
**Pull request by rukmini-basu-da**
Fixes https://github.com/hyperledger-labs/splice-wallet-kernel/issues/616

This fixes the `setup-exchange.ts` so it uses the app provider validator url rather than the app user validator url to align with the app provider participant configs. Additionally, this allows us to tap the exchange party to ensure there are enough funds to setup the transfer pre approval.

### CODE REVIEW

File: sdk/wallet-sdk/src/validatorController.ts [hunk 1]
```diff
@@ -255,3 +255,18 @@ export const localValidatorDefault = (
         token
     )
 }
+
+/**
+ * A default factory function used for running against a local validator node.
```
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/validatorController.ts]: this comment is wrong ? it uses the localnet and not the `yarn start:canton`

**Review by PHOL-DA — APPROVED** [review]
