### PR TITLE
fix(example-ping): ui rework

### LINKED ISSUE #1232: Status Changed event is fired every time the sdk.open() is called
whenever the sdk.open() is called a statusChanged event is fired, even if the status is the same as before.

### PR DESCRIPTION
**Pull request by PHOL-DA**
small update to the ping example alongside fixing a bug reported.

Add a fixture for the playwright tests to better capture what goes wrong.

also Fixes #1232.

image

### CODE REVIEW

File: core/wallet-test-utils/src/fixtures.ts [hunk 1]
```diff
@@ -0,0 +1,266 @@
...
+            }
+            networkLogs.push(entry)
+            console.warn(
+                `[${source}] HTTP ${response.status()}: ${response.url()}`
+            )
+        }
+    })
+}
+
+export const test = base.extend<{ page: Page }>({
```
Comment (alexmatson-da) [inline core/wallet-test-utils/src/fixtures.ts]: whats wrong with using the Playwright GUI? You get all this -- screenshots, console logs, network logs, and more out-of-the-box.

You can even inspect CI runs by downloading the report and opening it through the Playwright UI

Comment (alexmatson-da) [reply core/wallet-test-utils/src/fixtures.ts]: > add them to the GUI

which GUI do you mean?

Have you ever ran `yarn playwright test --ui`? I've been using this from the beginning to debug a failing playwright test and its really exceptional

# Timeline of screenshots (for all open windows, dapp & popup)

image

# Built-in console inspector

Screenshot 2026-02-04 at 7 14 01 AM



# Built-in network inspector 

including all headers, payloads, and responses

Screenshot 2026-02-04 at 7 14 54 AM
