### PR TITLE
fix: refactor utils namespace to create sdk offline

### LINKED ISSUE #1669: Offline SDK requires an active ledger connection
In example `14-offline-signing` we instantiate the offline wallet sdk like:
```
const offlineSdk = await SDK.create({
    auth: TOKEN_PROVIDER_CONFIG_DEFAULT,
    ledgerClientUrl: localNetStaticConfig.LOCALNET_APP_USER_LEDGER_URL,
})
```
An offline Wallet SDk should not require an active connection to the ledger.

### PR DESCRIPTION
**Pull request by rukmini-basu-da**
Fixes https://github.com/hyperledger-labs/splice-wallet-kernel/issues/1669

### CODE REVIEW

File: sdk/wallet-sdk/src/wallet/namespace/party/namespace.ts [hunk 1]
```diff
@@ -67,33 +63,4 @@ export class PartyNamespace {
 
         return Array.from(new Set(parties))
     }
-
-    /**
-     *
-     * @param preparedTransactions list of prepared topology transactions
-     * @returns a multihash combining all of the topology txs
-     */
-    public async hashTopologyTx(
```
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/wallet/namespace/party/namespace.ts:76]: we can't introduce breaking changes anymore, you will have to mark this as @deprecated and link to the new way of doing it

File: sdk/wallet-sdk/src/wallet/namespace/ledger/hash/namespace.ts [hunk 2]
```diff
@@ -1,17 +0,0 @@
-// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-// SPDX-License-Identifier: Apache-2.0
-
-import { PreparedTransaction } from '@canton-network/core-ledger-proto'
-import { SDKContext } from '../../../sdk.js'
-import { PreparedTransactionEncoder } from './util/encoder/preparedTransactionEncoder.js'
-
-export class PreparedTransactionNamespace {
```
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/wallet/namespace/ledger/hash/namespace.ts:8]: we still need to keep the old namespace for backwards compatability

File: sdk/wallet-sdk/src/wallet/namespace/utils/hash/util/encoder/types.ts
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/wallet/namespace/utils/hash/util/encoder/types.ts:1]: here as well we need to persist the old namespace for backwards compatability

File: sdk/wallet-sdk/src/wallet/namespace/utils/hash/util/const.ts
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/wallet/namespace/utils/hash/util/const.ts:1]: backward compatability

File: sdk/wallet-sdk/src/wallet/namespace/utils/hash/converter.ts
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/wallet/namespace/utils/hash/converter.ts:1]: backward compatability

File: sdk/wallet-sdk/src/wallet/namespace/utils/hash/index.ts
Comment (PHOL-DA) [inline sdk/wallet-sdk/src/wallet/namespace/utils/hash/index.ts:1]: backward compatability

**Review by PHOL-DA — APPROVED** [review]
