### PR TITLE
fix(core-ledger-client,wallet-sdk): pass access token to token standard service

### LINKED ISSUE #505: [Wallet SDK] Scan Proxy Bearer Token
currently the scan Proxy api  auth on certain endpoints.

Allow users to define authentication or use existing authentication for scan proxy.

Definition can be found here: https://docs.dev.sync.global/app_dev/validator_api/index.html#scan-proxy-api

### PR DESCRIPTION
**Pull request by PHOL-DA**
Fixes #505

### CODE REVIEW

File: docs/wallet-integration-guide/examples/config.ts [hunk 1]
```diff
@@ -4,4 +4,6 @@
 export const LOCALNET_SCAN_API_URL = new URL(
     'http://wallet.localhost:2000/api/validator'
 )
-export const LOCALNET_REGISTRY_API_URL = new URL('http://scan.localhost:4000')
+export const LOCALNET_REGISTRY_API_URL = new URL(
+    LOCALNET_SCAN_API_URL.href + '/v0/scan-proxy'
```
Comment (mjuchli-da) [inline docs/wallet-integration-guide/examples/config.ts:8]: would it possibly make sense to rename to 

```suggestion
    LOCALNET_VALIDATOR_URL.href + '/v0/scan-proxy'
```

**Review by mjuchli-da — APPROVED** [review]
