### PR TITLE
fix(wallet-gateway-remote): fix wallet sync report

### LINKED ISSUE #1634: Fix wallet sync report
After wallet sync runs, server returns amount of added, updated and disabled wallets and UI displays a toast with that info. 
It should return changes in current iteration of sync, but if there were disabled wallets before, `updated` and `disabled` counts are increased by amount of already disabled wallets for each response.

### PR DESCRIPTION
**Pull request by pawelstepien-da**
Fix wrong counts of updated and disabled in message that shows after wallet sync - pre-existing disabled wallets were wrongly increasing updated and disabled counts in each call.
Add tests for sync report.
Reduce amount of calls to `/v2/parties/participant-id` to one per wallet sync.

### CODE REVIEW

File: wallet-gateway/remote/src/ledger/wallet-sync-service.ts [hunk 1]
```diff
@@ -531,24 +545,36 @@ export class WalletSyncService {
...
-                    updated: [...walletsWithoutParty, ...rightsUpdatedWallets],
-                    disabled: disabled,
+                    added,
+                    updated,
+                    disabled,
                 },
                 'Wallet sync completed.'
             )
 
+            // added - non disabled wallets added in this sync call
```
Comment (PHOL-DA) [inline wallet-gateway/remote/src/ledger/wallet-sync-service.ts]: would it make more sense to have these as descriptors on the returned object (`SyncWalletsResult`) instead of line comments ?

**Review by PHOL-DA — APPROVED** [review]

File: wallet-gateway/remote/src/ledger/wallet-sync-service.ts (hunk 1 above)
Comment (pawelstepien-da) [reply wallet-gateway/remote/src/ledger/wallet-sync-service.ts]: great idea

**Review by mjuchli-da — APPROVED** [review]
thanks!

**Review by PHOL-DA — APPROVED** [review]
